### ISSUE TITLE
Flatpak?

### ISSUE THREAD

**Issue by alvarlagerlof** [Captain-Chaos/WorldPainter#214]
Would it be possible to build this as a [Flatpak](https://flatpak.org/) for publishing to [Flathub](https://flathub.org/home)?

**Comment by Captain-Chaos** [comment]
Interesting. Maybe; I'll take a look. The WorldPainter distribution is built by [Install4J](https://www.ej-technologies.com/products/install4j/overview.html), so it would have to support it, or it would have to be easy to build on one of the installers generated by Install4J.

**Comment by alvarlagerlof** [comment]
> But I have to say I'm getting strong flavours of [xkcd](https://xkcd.com/927/).

I get that. But it's not looking like a fad to me. I have the 99% of my apps on it with very minimal complaints and much higher stability than before (due to dependencies being way way more likely to be correct) Definelty worth checking out.

**Comment by JakobDev** [comment]
Maybe it's currently the best to use the portable version e.g. https://www.worldpainter.net/files/worldpainter_2.12.0.tar.gz and put it in a Flatpak. This would exclude ARM Devices, but it's better than nothing. I can try to create a manifest if you want.

**Comment by Captain-Chaos** [comment]
@JakobDev Why would that exclude Arm? As long as the correct version of Java (preferably at least version 11) is present, it should run. Does Flatpak have a way to specify that dependency and have it automatically fulfilled?

**Comment by JakobDev** [comment]
> Why would that exclude Arm?

If you take a look at the linked archive, it included 2 .so files. These files are native libs. If Worldpainter can run without these 2 files, it can also run on ARM.

> Does Flatpak have a way to specify that dependency and have it automatically fulfilled?

Yes.

I have created a Manifest:
```yaml
app-id: net.worldpainter.worldpainter
runtime: org.freedesktop.Platform
runtime-version: '21.08'
sdk: org.freedesktop.Sdk
command: worldpainter
sdk-extensions:
  - org.freedesktop.Sdk.Extension.openjdk
finish-args:
  - --env=INSTALL4J_JAVA_HOME=/app/jre
  - --filesystem=host:rw
  - --socket=x11
  - --device=dri
  - --share=ipc

modules:
  - name: java
    buildsystem: simple
    build-commands:
      - /usr/lib/sdk/openjdk/install.sh

  - name: worldpainter
    buildsystem: simple
    build-commands:
      - mkdir -p $FLATPAK_DEST/lib
      - mkdir -p $FLATPAK_DEST/bin
      - cp -r worldpainter $FLATPAK_DEST/lib
      - ln -s $FLATPAK_DEST/lib/worldpainter/worldpainter $FLATPAK_DEST/bin/worldpainter
    sources:
      - type: archive
        url: https://www.worldpainter.net/files/worldpainter_2.12.0.tar.gz
        sha256: 7427c18d521c20d60bd23c578e726671f23c3516503fc5a7449f8c0c5cdd805b
        dest: worldpainter
```
Save it as net.worldpainter.worldpainter.

First install flatpak-builder with `flatpak install org.flatpak.Builder`. After you've done taht you can build and install it with:
```
flatpak run org.flatpak.Builder build-dir net.worldpainter.worldpainter.yaml --force-clean --ccache --install-deps-from=flathub --install --user
```
After that you can run it with `flatpak run net.worldpainter.worldpainter`. The package is currently missing a .desktop and a AppStream file, but after you've added this, the package is ready. You need also your Icon in the size 128x128.

There is one big issue with Worldpainter itself: Worldpainter saves all of his data in `$HOME/.worldpainter`. This is the wrong directory. Please follow the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). That menas for you: If `XDG_DATA_HOME` save your data in `$XDG_DATA_HOME/worldpainter`. If not save it in `$HOME/.local/share/worldpainter`.
